Repository D8-X/d8x-trader-frontend-lite, pull requests merged in 2023-11, with the labels that each got.

#409 Align Slippage settings and leverage blocks
  src/components/order-block/elements/leverage-selector/LeverageSelector.module.scss
  src/components/order-block/elements/order-settings/OrderSettings.module.scss
Labels: bug

#413 Update favicons and manifest.json
  README.md
  public/android-chrome-144x144.png
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/manifest.json
  public/safari-pinned-tab.svg
  src/assets/interactive-logo/InteractiveLogo.module.scss
  src/assets/interactive-logo/InteractiveLogo.tsx
  src/assets/logo.svg
  src/assets/logoWithText.svg
  src/assets/logo_with_text.svg
  src/components/header/EmptyHeader.tsx
  src/components/header/Header.tsx
  src/components/positions-table/elements/modals/share-modal/ShareModal.tsx
Labels: enhancement

#419 update manifest
  public/manifest.json
  src/blockchain-api/approveMarginToken.ts
Labels: enhancement

#426 Fix geonames.js library deps
  package-lock.json
Labels: bug, enhancement

#429 Add ability to hide LiFi widget when use testnet
  .env.example
  .github/workflows/k8s-dev.yaml
  .github/workflows/k8s.yaml
  README.md
  src/components/wallet-connect-button/WalletConnectButton.tsx
  src/config.ts
Labels: enhancement

#430 Add VITE_ACTIVATE_LIFI arg to the Dockerfile
  Dockerfile
Labels: bug, enhancement

#435 Add key to enable/disable GeoBlocking check in background
  src/context/geo-blocking-context/GeoBlockingContext.tsx
Labels: enhancement

#436 Add link to External Service Status
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/en/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  public/locales/kr/translations.json
  src/components/footer/Footer.module.scss
  src/components/footer/Footer.tsx
Labels: enhancement
