Repository D8-X/d8x-trader-frontend-lite, pull requests merged in 2024-03, with the labels that each got.

#531 Implement PumpStation page
  .env.example
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/en/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  public/locales/kr/translations.json
  src/assets/logos/d8xLogo.svg
  src/assets/logos/d8xLogoWithText.svg
  src/components/funding-table/FundingTable.tsx
  src/components/header/Header.module.scss
  src/components/header/Header.tsx
  src/components/header/elements/settings-block/components/one-click-trading/components/FundingModal.tsx
  src/components/order-block/elements/action-block/ActionBlock.tsx
  src/components/usdc-swap-widget/UsdcSwapWidget.tsx
  src/config.ts
  src/context/websocket-context/d8x/types.ts
  src/context/websocket-context/d8x/useWsMessageHandler.tsx
  src/network/network.ts
  src/pages/portfolio-page/store/fetchPoolTokensUSDBalance.ts
  src/pages/pump-station-page/PumpStationPage.module.scss
  src/pages/pump-station-page/PumpStationPage.tsx
  src/pages/pump-station-page/components/overview/Overview.module.scss
  src/pages/pump-station-page/components/overview/Overview.tsx
  src/pages/pump-station-page/components/pump-o-meter/PumpOMeter.module.scss
  src/pages/pump-station-page/components/pump-o-meter/PumpOMeter.tsx
  src/pages/pump-station-page/components/pump-station-block/PumpStationBlock.module.scss
  src/pages/pump-station-page/components/pump-station-block/PumpStationBlock.tsx
  src/pages/pump-station-page/components/pump-stats/PumpStats.module.scss
  src/pages/pump-station-page/components/pump-stats/PumpStats.tsx
  src/pages/trader-page/components/table-data-refetcher/TableDataFetcher.tsx
  src/routes/RoutesE.ts
  src/routes/pages.ts
  src/routes/routes.tsx
  src/store/pools.store.ts
  src/styles/colors.scss
  src/styles/darkColors.scss
  src/types/types.ts
Labels: enhancement

#533 Implement `Maintenance mode` block
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/en/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  public/locales/kr/translations.json
  src/components/footer/Footer.tsx
  src/components/header/Header.module.scss
  src/components/maintenance-wrapper/MaintenanceWrapper.module.scss
  src/components/maintenance-wrapper/MaintenanceWrapper.tsx
  src/network/network.ts
  src/pages/portfolio-page/PortfolioPage.tsx
  src/pages/refer-page/ReferPage.module.scss
  src/pages/refer-page/ReferPage.tsx
  src/pages/trader-page/TraderPage.module.scss
  src/pages/trader-page/TraderPage.tsx
  src/pages/vault-page/VaultPage.module.scss
  src/pages/vault-page/VaultPage.tsx
  src/types/types.ts
Labels: enhancement

#542 Adjust sizes for fields and fix Wrong Network button
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/en/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  src/assets/networks/arbitrumSepolia.chain.svg
  src/components/header/elements/market-select/MarketSelect.module.scss
  src/components/info-label-block/InfoLabelBlock.module.scss
  src/components/order-block/elements/limit-price/LimitPrice.module.scss
  src/components/order-block/elements/order-type-selector/OrderTypeSelector.module.scss
  src/components/order-block/elements/trigger-price/TriggerPrice.module.scss
  src/components/responsive-input/ResponsiveInput.module.scss
  src/components/stats-line/StatsLine.module.scss
  src/network/network.ts
  src/pages/pump-station-page/components/overview/Overview.module.scss
  src/pages/pump-station-page/components/pump-station-block/PumpStationBlock.tsx
  src/pages/trader-page/components/perpetual-stats/PerpetualStats.module.scss
  src/styles/colors.scss
  src/styles/darkColors.scss
  src/styles/theme/theme.ts
  src/types/types.ts
Labels: bug, enhancement

#545 Create trigger for balances update after trade
  src/components/header/Header.tsx
  src/components/order-block/elements/info-block/InfoBlock.tsx
  src/components/order-block/elements/order-size/OrderSize.tsx
  src/components/order-block/elements/order-size/components/OrderSizeSlider.tsx
  src/context/websocket-context/d8x/useWsMessageHandler.tsx
  src/pages/trader-page/components/table-data-refetcher/TableDataFetcher.tsx
  src/store/pools.store.ts
Labels: bug, enhancement

#546 Fix private key reveal for Social login
  package-lock.json
  package.json
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/en/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  public/locales/kr/translations.json
  src/components/extract-pk-modal/ExtractPKModal.tsx
  src/context/web3-auth-context/Web3AuthContext.tsx
  src/pages/pump-station-page/components/pump-station-block/PumpStationBlock.module.scss
  src/pages/pump-station-page/components/pump-station-block/PumpStationBlock.tsx
  src/store/web3-auth.store.ts
Labels: bug

#551 Implement Gas deposit checker
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/en/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  public/locales/kr/translations.json
  src/appConstants.ts
  src/blockchain-api/approveMarginToken.ts
  src/blockchain-api/contract-interactions/removeDelegate.ts
  src/blockchain-api/getGasLimit.ts
  src/blockchain-api/transferFunds.ts
  src/components/funding-table/elements/FundingRow.tsx
  src/components/funding-table/elements/funding-block/FundingBlock.tsx
  src/components/gas-deposit-checker/GasDepositChecker.tsx
  src/components/header/Header.tsx
  src/components/header/elements/settings-block/components/one-click-trading/components/FundingModal.module.scss
  src/components/header/elements/settings-block/components/one-click-trading/components/FundingModal.tsx
  src/components/header/elements/settings-block/components/one-click-trading/components/OneClickTradingModal.tsx
  src/components/open-orders-table/OpenOrdersTable.tsx
  src/components/order-block/elements/action-block/ActionBlock.tsx
  src/components/positions-table/elements/modals/close-modal/CloseModal.tsx
  src/components/positions-table/elements/modals/modify-modal/ModifyModal.tsx
  src/components/positions-table/elements/modals/modify-tp-sl-modal/ModifyTpSlModal.tsx
  src/components/positions-table/helpers/cancelOrders.tsx
  src/components/trade-history-table/elements/TradeHistoryRow.tsx
  src/components/trade-history-table/elements/trade-history-block/TradeHistoryBlock.tsx
  src/components/wallet-balances/WalletBalances.tsx
  src/components/wallet-balances/constants.ts
  src/components/wallet-balances/elements/pool-line/PoolLine.tsx
  src/context/user-wallet-context/UserWalletContext.tsx
  src/index.tsx
  src/pages/vault-page/components/liquidity-block/LiquidityBlock.tsx
  src/pages/vault-page/components/liquidity-block/elements/actions/Add.tsx
  src/pages/vault-page/components/liquidity-block/elements/actions/Initiate.tsx
  src/pages/vault-page/components/liquidity-block/elements/actions/Withdraw.tsx
  src/types/enums.ts
Labels: enhancement

#553 Adjust Boost station to follow new design and API
  .env.example
  public/images/boost-station/rocket.png
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/en/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  public/locales/kr/translations.json
  src/components/header/elements/connect-modal/ConnectModal.tsx
  src/components/positions-table/PositionsTable.tsx
  src/config.ts
  src/network/network.ts
  src/pages/boost-station-page/BoostStationPage.module.scss
  src/pages/boost-station-page/BoostStationPage.tsx
  src/pages/boost-station-page/components/boost-meter/BoostMeter.module.scss
  src/pages/boost-station-page/components/boost-meter/BoostMeter.tsx
  src/pages/boost-station-page/components/boost-station-block/BoostStationBlock.module.scss
  src/pages/boost-station-page/components/boost-station-block/BoostStationBlock.tsx
  src/pages/boost-station-page/components/boost-stats/BoostStats.module.scss
  src/pages/boost-station-page/components/boost-stats/BoostStats.tsx
  src/pages/boost-station-page/components/overview/Overview.module.scss
  src/pages/boost-station-page/components/overview/Overview.tsx
  src/pages/pump-station-page/components/overview/Overview.tsx
  src/pages/pump-station-page/components/pump-station-block/PumpStationBlock.module.scss
  src/pages/pump-station-page/components/pump-station-block/PumpStationBlock.tsx
  src/pages/pump-station-page/components/pump-stats/PumpStats.tsx
  src/routes/RoutesE.ts
  src/routes/pages.ts
  src/routes/routes.tsx
  src/types/types.ts
Labels: enhancement

#554 deposit gas to trading wallet
  src/App.tsx
  src/blockchain-api/contract-interactions/removeDelegate.ts
  src/blockchain-api/getGasPrice.ts
  src/components/atoms-global-updates/AtomsGlobalUpdates.tsx
  src/components/deposit-modal/DepositModal.tsx
  src/components/gas-deposit-checker/GasDepositChecker.tsx
  src/components/header/elements/settings-block/SettingsBlock.tsx
  src/components/header/elements/settings-block/components/one-click-trading/OneClickTradingButton.tsx
  src/components/positions-table/elements/modals/modify-tp-sl-modal/ModifyTpSlModal.tsx
  src/components/positions-table/elements/modals/modify-tp-sl-modal/components/StopLossSelector.tsx
  src/components/positions-table/elements/modals/modify-tp-sl-modal/components/TakeProfitSelector.tsx
  src/components/wallet-connect-button/OneClickTradingButton.tsx
  src/components/wallet-connect-button/components/funding-modal/FundingModal.module.scss
  src/components/wallet-connect-button/components/funding-modal/FundingModal.tsx
  src/components/wallet-connect-button/components/one-click-trading-modal/OneClickTradingModal.module.scss
  src/components/wallet-connect-button/components/one-click-trading-modal/OneClickTradingModal.tsx
  src/context/user-wallet-context/UserWalletContext.tsx
  src/pages/vault-page/components/personal-stats/PersonalStats.tsx
  src/store/global-modals.store.ts
Labels: bug, enhancement

#555 Show `reduce-only` only for active positions
  src/components/order-block/elements/order-settings/OrderSettings.tsx
  src/pages/trader-page/components/table-data-refetcher/TableDataFetcher.tsx
Labels: bug, enhancement

#557 Unsubscribe from lost pair for candles WS
  src/components/header/elements/market-select/MarketSelect.tsx
  src/pages/trader-page/components/candles-webSocket-listener/helpers/createPairWithPeriod.ts
  src/pages/trader-page/components/candles-webSocket-listener/subscribingCheckAtom.ts
  src/pages/trader-page/components/candles-webSocket-listener/useCandleMarketsSubscribe.ts
  src/pages/trader-page/components/candles-webSocket-listener/useCandlesWsMessageHandler.ts
Labels: bug

#559 Add tooltips for stats blocks
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/en/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  public/locales/kr/translations.json
  src/components/funding-table/elements/funding-block/FundingBlock.tsx
  src/components/header/elements/settings-button/SettingsButton.tsx
  src/components/open-orders-table/elements/open-order-block/OpenOrderBlock.tsx
  src/components/order-block/elements/info-block/InfoBlock.tsx
  src/components/positions-table/PositionsTable.tsx
  src/components/positions-table/elements/modals/modify-modal/ModifyModal.tsx
  src/components/positions-table/elements/position-block/PositionBlock.tsx
  src/components/referral-confirm-modal/ReferralConfirmModal.tsx
  src/components/sides-row/SidesRow.module.scss
  src/components/sides-row/SidesRow.tsx
  src/components/stats-line/StatsLine.module.scss
  src/components/stats-line/StatsLine.tsx
  src/components/stats-line/types.ts
  src/components/table/sortable-header/SortableHeaders.module.scss
  src/components/table/sortable-header/SortableHeaders.tsx
  src/components/tooltip-mobile/TooltipMobile.tsx
  src/components/trade-history-table/elements/trade-history-block/TradeHistoryBlock.tsx
  src/network/referral.ts
  src/pages/refer-page/components/add-partner-dialog/AddPartnerDialog.tsx
  src/pages/refer-page/components/create-referrer-code-dialog/CreateReferrerCodeDialog.tsx
  src/pages/refer-page/components/enter-code-dialog/EnterCodeDialog.tsx
  src/pages/refer-page/components/referrals-block/ReferralsBlock.tsx
  src/pages/refer-page/hooks.ts
  src/pages/trader-page/components/perpetual-stats/PerpetualStats.module.scss
  src/pages/trader-page/components/perpetual-stats/PerpetualStats.tsx
  src/types/types.ts
Labels: enhancement

#561 Add max field for `Add Collateral`
  public/locales/es/translations.json
  src/components/positions-table/elements/modals/modify-modal/ModifyModal.tsx
  src/components/positions-table/elements/modals/modify-tp-sl-modal/ModifyTpSlModal.tsx
Labels: bug
