Repository D8-X/d8x-trader-frontend-lite, pull requests merged in 2024-04, with the labels that each got.

#568 Show deposits based on Strategy address
  src/components/deposit-modal/DepositModal.tsx
  src/components/gas-deposit-checker/GasDepositChecker.tsx
  src/components/wallet-balances/WalletBalances.tsx
  src/components/wallet-balances/elements/pool-line/PoolLine.tsx
  src/context/user-wallet-context/UserWalletContext.tsx
  src/store/app.store.ts
Labels: enhancement

#570 Add phases step-by-step help texts on loading
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/en/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  public/locales/kr/translations.json
  src/blockchain-api/contract-interactions/enterStrategy.ts
  src/blockchain-api/contract-interactions/exitStrategy.ts
  src/components/header/Header.tsx
  src/components/header/elements/collaterals-select/CollateralsSelect.tsx
  src/components/li-fi-widget/LiFiWidgetHolder.tsx
  src/components/open-orders-table/OpenOrdersTable.tsx
  src/components/positions-table/PositionsTable.tsx
  src/components/positions-table/elements/modals/modify-modal/ModifyModal.tsx
  src/components/sdk-loader/SDKLoader.tsx
  src/components/trade-history-table/TradeHistoryTable.tsx
  src/pages/portfolio-page/PortfolioPage.tsx
  src/pages/portfolio-page/components/AccountValue/AccountValue.tsx
  src/pages/portfolio-page/store/fetchPoolShare.ts
  src/pages/portfolio-page/store/fetchPortfolio.ts
  src/pages/portfolio-page/store/fetchStrategySyntheticPosition.ts
  src/pages/portfolio-page/store/fetchUnrealizedPnL.ts
  src/pages/refer-page/components/referrer-tab/ReferrerTab.tsx
  src/pages/refer-page/components/trader-tab/TraderTab.tsx
  src/pages/strategies-page/components/enter-strategy/EnterStrategy.module.scss
  src/pages/strategies-page/components/enter-strategy/EnterStrategy.tsx
  src/pages/strategies-page/components/exit-strategy/ExitStrategy.module.scss
  src/pages/strategies-page/components/exit-strategy/ExitStrategy.tsx
  src/pages/strategies-page/components/strategy-block/StrategyBlock.tsx
  src/pages/trader-page/components/PoolSubscription.tsx
  src/store/strategies.store.ts
Labels: bug, enhancement

#571 Improve page first load and add check for poolId on Portfolio page
  src/components/header/Header.tsx
  src/pages/portfolio-page/PortfolioPage.tsx
Labels: bug

#574 Fix pool usage for selected position in the positions table
  package-lock.json
  package.json
  src/components/positions-table/PositionsTable.tsx
  src/components/positions-table/elements/modals/close-modal/CloseModal.tsx
  src/components/positions-table/elements/modals/modify-modal/ModifyModal.tsx
  src/components/positions-table/elements/modals/modify-tp-sl-modal/ModifyTpSlModal.tsx
  src/components/positions-table/hooks/usePoolTokenBalance.ts
  src/store/pools.store.ts
Labels: bug

#576 Wrap/unwrap OKB token on 196 chain
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/en/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  public/locales/kr/translations.json
  src/blockchain-api/contract-interactions/wrapOKB.ts
  src/components/deposit-modal/DepositModal.module.scss
  src/components/deposit-modal/DepositModal.tsx
  src/components/deposit-modal/elements/okx-convertor/OKXConvertor.tsx
  src/components/funding-table/FundingTable.module.scss
  src/components/header/Header.tsx
  src/components/header/elements/connect-modal/ConnectModal.module.scss
  src/components/header/elements/connect-modal/ConnectModal.tsx
  src/components/open-orders-table/OpenOrdersTable.tsx
  src/components/order-block/OrderBlock.module.scss
  src/components/order-block/OrderBlock.tsx
  src/components/order-block/elements/action-block/ActionBlock.tsx
  src/components/positions-table/elements/modals/close-modal/CloseModal.tsx
  src/components/positions-table/elements/modals/modify-tp-sl-modal/ModifyTpSlModal.tsx
  src/components/separator/OrSeparator.tsx
  src/components/separator/Separator.module.scss
  src/components/wallet-balances/WalletBalances.tsx
  src/components/wallet-balances/elements/pool-line/PoolLine.tsx
  src/components/wallet-connect-button/components/funding-modal/hooks/useFundingTransfer.tsx
  src/components/withdraw-modal/WithdrawModal.module.scss
  src/components/withdraw-modal/WithdrawModal.tsx
  src/components/withdraw-modal/hooks/useTransferGasToken.tsx
  src/components/withdraw-modal/hooks/useTransferTokens.tsx
  src/pages/strategies-page/components/enter-strategy/hooks/useEnterStrategy.tsx
  src/pages/strategies-page/components/exit-strategy/hooks/useExitStrategy.tsx
  src/pages/strategies-page/components/strategy-block/hooks/useClaimFunds.tsx
  src/pages/vault-page/components/liquidity-block/elements/actions/Add.tsx
  src/pages/vault-page/components/liquidity-block/elements/actions/Initiate.tsx
  src/pages/vault-page/components/liquidity-block/elements/actions/Withdraw.tsx
  src/types/types.ts
Labels: enhancement

#578 re-route through sdk
  package-lock.json
  package.json
  src/blockchain-api/contract-interactions/exitStrategy.ts
  src/components/open-orders-table/OpenOrdersTable.tsx
  src/components/positions-table/PositionsTable.tsx
  src/components/positions-table/elements/modals/modify-modal/ModifyModal.tsx
  src/components/wallet-connect-button/components/one-click-trading-modal/OneClickTradingModal.tsx
  src/pages/strategies-page/components/exit-strategy/ExitStrategy.tsx
  src/pages/strategies-page/components/strategy-block/StrategyBlock.tsx
  src/pages/trader-page/components/PerpetualInfoFetcher.tsx
  src/pages/trader-page/components/table-data-refetcher/TableDataFetcher.tsx
Labels: bug, enhancement

#579 Improve UI/UX for buttons
  src/components/open-orders-table/OpenOrdersTable.tsx
  src/components/positions-table/elements/modals/close-modal/CloseModal.tsx
  src/components/positions-table/elements/modals/modify-modal/ModifyModal.tsx
  src/components/positions-table/elements/modals/modify-tp-sl-modal/ModifyTpSlModal.tsx
  src/components/positions-table/elements/modals/modify-tp-sl-modal/components/StopLossSelector.tsx
  src/components/positions-table/elements/modals/modify-tp-sl-modal/components/TakeProfitSelector.tsx
Labels: enhancement

#580 Fix issue with GeoBlocking check by IP
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  src/components/header/Header.tsx
  src/context/geo-blocking-context/GeoBlockingContext.tsx
Labels: bug

#582 Improve functionality for Vault page
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/en/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  public/locales/kr/translations.json
  src/blockchain-api/generateDelegate.ts
  src/blockchain-api/generateStrategyAccount.ts
  src/blockchain-api/getStorageKey.ts
  src/blockchain-api/getStrategyAddress.ts
  src/components/atoms-global-updates/AtomsGlobalUpdates.tsx
  src/components/currency-selector/types.ts
  src/components/gas-deposit-checker/GasDepositChecker.tsx
  src/components/order-block/elements/action-block/ActionBlock.tsx
  src/components/positions-table/helpers/cancelOrders.tsx
  src/components/positions-table/hooks/usePoolTokenBalance.ts
  src/helpers/getDelegateKey.ts
  src/hooks/useEthersSigner.ts
  src/pages/portfolio-page/components/AssetsBlock/tabs/Tabs.module.scss
  src/pages/portfolio-page/components/AssetsBlock/tabs/Tabs.tsx
  src/pages/portfolio-page/store/fetchEarnings.ts
  src/pages/portfolio-page/store/fetchPoolShare.ts
  src/pages/portfolio-page/store/fetchPoolTokensUSDBalance.ts
  src/pages/portfolio-page/store/fetchPortfolio.ts
  src/pages/portfolio-page/store/fetchRealizedPnL.ts
  src/pages/portfolio-page/store/fetchStrategySyntheticPosition.ts
  src/pages/portfolio-page/store/fetchUnrealizedPnL.ts
  src/pages/vault-page/VaultPage.tsx
  src/pages/vault-page/components/global-stats/GlobalStats.tsx
  src/pages/vault-page/components/liquidity-block/LiquidityBlock.tsx
  src/pages/vault-page/components/liquidity-block/elements/actions/Add.tsx
  src/pages/vault-page/components/liquidity-block/elements/actions/Initiate.tsx
  src/pages/vault-page/components/liquidity-block/elements/actions/Withdraw.tsx
  src/pages/vault-page/components/liquidity-block/elements/liquidity-type-selector/LiquidityTypeSelector.module.scss
  src/pages/vault-page/components/liquidity-block/elements/liquidity-type-selector/LiquidityTypeSelector.tsx
  src/store/app.store.ts
  src/types/types.ts
Labels: bug, enhancement

#583 Retry exchange-info call with SDK
  src/components/header/Header.tsx
Labels: bug, enhancement

#586 Fix issue with chain icons (SVGs)
  src/assets/networks/arbitrum.png
  src/assets/networks/polygon.webp
  src/assets/networks/polygonZkEvm.png
  src/blockchain-api/wagmi/wagmiClient.ts
Labels: bug

#588 Fix Web3Auth optional state and update readme
  README.md
  src/context/web3-auth-context/Web3AuthContext.tsx
Labels: bug

#592 Change Polygon/Cardona chain icon
  src/assets/networks/polygonZkEVM_white.png
  src/blockchain-api/wagmi/wagmiClient.ts
Labels: enhancement

#595 Fix `npm start` and check OrderSizeSlider
  package-lock.json
  package.json
  src/components/order-block/elements/order-size/components/OrderSizeSlider.tsx
  src/pages/boost-station-page/components/boost-station-block/BoostStationBlock.module.scss
  src/utils/getDynamicLogo.ts
  vite.config.mts
Labels: bug, enhancement

#600 Refresh app in case update is received
  public/locales/cn/translations.json
  public/locales/de/translations.json
  public/locales/en/translations.json
  public/locales/es/translations.json
  public/locales/fr/translations.json
  public/locales/kr/translations.json
  src/assets/crypto-icons/generic.svg
  src/components/app-reload/AppReload.module.scss
  src/components/app-reload/AppReload.tsx
  src/components/gas-deposit-checker/GasDepositChecker.tsx
  src/context/user-wallet-context/UserWalletContext.tsx
  src/routes/routes.tsx
  src/utils/getDynamicLogo.ts
Labels: enhancement

#604 Apply default theme from env variables
  .env.example
  README.md
  package-lock.json
  package.json
  src/RainbowKitProviderWrapper.tsx
  src/ToastContainerWrapper.tsx
  src/components/positions-table/elements/modals/share-modal/Background.tsx
  src/components/theme-applier/ThemeApplier.tsx
  src/components/trading-view-chart/elements/chart-block/ChartBlock.tsx
  src/config.ts
  src/store/app.store.ts
  src/types/enums.ts
Labels: enhancement
